<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <VersionPrefix>0.6.0</VersionPrefix>
    <Authors>Ultimate Duckov Statistics contributors</Authors>
    <Copyright>Copyright (c) 2026 Ultimate Duckov Statistics contributors</Copyright>
  </PropertyGroup>
</Project>
