namespace UltimateDuckovStatistics.UI;

internal static class UiText
{
    private static readonly Dictionary<string, string> English =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["ui.title"] = "Ultimate Duckov Statistics",
            ["ui.close"] = "Close",
            ["ui.overview"] = "Overview",
            ["ui.items"] = "Items",
            ["ui.runs"] = "Runs",
            ["ui.records"] = "Records",
            ["ui.diagnostics"] = "Diagnostics",
            ["ui.total_uses"] = "Successful raid uses",
            ["ui.actual_hp"] = "Actual HP restored",
            ["ui.save_slot"] = "Save slot",
            ["ui.generation"] = "UDS generation",
            ["ui.interrupted_sessions"] = "Interrupted sessions recovered",
            ["ui.total_runs"] = "Runs",
            ["ui.extracted_runs"] = "Extracted",
            ["ui.died_runs"] = "Died",
            ["ui.interrupted_runs"] = "Interrupted",
            ["ui.physical_distance"] = "Physical distance",
            ["ui.teleport_distance"] = "Teleport/excluded distance",
            ["ui.no_runs"] = "No completed runs recorded for this save generation.",
            ["ui.no_records"] = "No eligible extraction or death duration records recorded.",
            ["ui.outcome"] = "Outcome",
            ["ui.map"] = "Map",
            ["ui.active_time"] = "Active time",
            ["ui.wall_time"] = "Wall-clock diagnostic",
            ["ui.shortest"] = "Shortest",
            ["ui.longest"] = "Longest",
            ["ui.extraction_records"] = "Extraction records",
            ["ui.death_records"] = "Death records",
            ["ui.per_map"] = "Per-map totals and records",
            ["ui.unsupported"] = "Unsupported",
            ["ui.group_totals"] = "Canonical groups",
            ["ui.no_items"] = "No successful raid item uses recorded for this save generation.",
            ["ui.item_name"] = "Item",
            ["ui.group"] = "Group",
            ["ui.activations"] = "Activations",
            ["ui.amount"] = "Amount consumed",
            ["ui.capabilities"] = "Adapter capabilities",
            ["ui.diagnostic_log"] = "Recent bounded diagnostics",
            ["ui.data_path"] = "Data path",
            ["ui.export"] = "Export JSON + CSV",
            ["ui.reset"] = "Reset this UDS profile",
            ["ui.reset_warning"] = "Reset archives the current UDS generation read-only and starts at zero. Duckov saves are not changed.",
            ["ui.confirm_reset"] = "Confirm reset",
            ["ui.cancel"] = "Cancel",
            ["ui.hotkey"] = "Panel hotkey",
            ["ui.apply"] = "Apply",
            ["ui.hotkey_invalid"] = "Unknown Unity key name; hotkey was not changed.",
            ["ui.hotkey_saved"] = "Panel hotkey saved.",
            ["ui.raid_unavailable"] = "Statistics are available outside raids.",
            ["ui.export_complete"] = "Export complete",
            ["ui.export_failed"] = "Export failed; see Diagnostics and Player.log.",
            ["ui.reset_complete"] = "UDS profile reset; prior generation archived read-only.",
            ["ui.integrity_note"] = "Run time excludes pause/loading. Physical and teleport/excluded distance are separate. Integrity-flagged and interrupted runs remain visible but do not enter default duration records.",
            ["ui.open_hint"] = "Press the configured hotkey outside raids to show or hide this panel."
        };

    public static string Get(string key) => English.TryGetValue(key, out var value) ? value : key;
}
